[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](
https://colab.research.google.com/github/choROPeNt/gzlb/blob/main/notebooks/GZLB-UE6.5.ipynb
)

# GZLB
## UE6: Anisotropes Werkstoffverhalten, Verallgemeinertes Hooke'sches Gesetz, Festigkeitshypothesen



### Aufgabe 6.5: Spannungsanalyse (3D)

gesucht für den Spannunsgtensor 

$$\underline{\underline{\sigma}}=\begin{bmatrix}130 & -40 & 0\\-40 & 70 & 0\\ 0 & 0  & 5\end{bmatrix} \text{MPa}$$

die Hautpnormalspannungen $\sigma_I$, $\sigma_{II}$ und $\sigma_{III}$ (Eigenwerte) sowie ihre korrespondierenden Richtungen $\underline{v}_I$, $\underline{v}_{II}$ und $\underline{v}_{III}$ mit $\underline{v}=(v_x,v_y,v_z)^\intercal$

#### Schritt 1
importieren des Packages Numpy

In [1]:
import numpy as np

#### Schritt 2
erstellen des Spannungstensors $\underline{\underline{\sigma}}$ als numpy-array mit dem Namen `stress`

In [2]:
stress = np.array([[130,-40,0],
                    [-40,70,0],
                    [0,0,5]])

print("Werte des array stress:\n",stress)
print("Dimensionen des array stress:", stress.shape)

Werte des array stress:
 [[130 -40   0]
 [-40  70   0]
 [  0   0   5]]
Dimensionen des array stress: (3, 3)


#### Berechnung der Eigenwerte und Eigenvektoren

das Eigenwertproblem ist wie folgt definiert

$$ \left( \underline{\underline{\sigma}}-\lambda \underline{\underline{E}}\right)\underline{v}=0$$

$$ \det \begin{vmatrix}\left( \underline{\underline{\sigma}}-\lambda \underline{\underline{E}}\right)\end{vmatrix}=0 \qquad \forall \underline{v}\neq0$$

in der Library `numpy.linagl` finden Sie die Funktion `eig(a)` zur Lösung des Eigenwertproblems $\lambda_i$ und zur Berechnung der rechten Eigenvektoren $\underline{v}_i$

In [3]:
w ,v = np.linalg.eig(stress)

In [4]:
for i, (eigenwert, eigenvektor) in enumerate(zip(w,v)):
    print()
    print("%s Eigenwert %.2f " %(i+1,eigenwert,))
    print("Mit den Eigenvektore:\n", eigenvektor)


1 Eigenwert 150.00 
Mit den Eigenvektore:
 [0.89442719 0.4472136  0.        ]

2 Eigenwert 50.00 
Mit den Eigenvektore:
 [-0.4472136   0.89442719  0.        ]

3 Eigenwert 5.00 
Mit den Eigenvektore:
 [0. 0. 1.]


### Berechnung des Winkels zwischen zwei Vektoren

$$ \alpha = \arccos \left ( \frac{\underline{v}_1\cdot\underline{v}_2}{|\underline{v}_1||\underline{v}_2|} \right)$$

dabei sind 

$$ \underline{v}_1\cdot\underline{v}_2 = \begin{pmatrix}v_{1,1}\\ \vdots \\ v_{1,n} \end{pmatrix} \cdot \begin{pmatrix}v_{2,1}\\ \vdots \\ v_{2,n} \end{pmatrix} = \sum_{i=1}^n v_{1,i}v_{2,i} $$

und 
$$ |\underline{v}| = \sqrt{\sum_{i=1}^n (v_{i})^2} $$


In [5]:
def angle_rad(v1, v2):
    """ 
        Returns the angle in radians between vectors 'v1' and 'v2'::
        using the scalar product
    """
    v1_u = unit_vector(v1)      ## normalized/unit vector
    v2_u = unit_vector(v2)      ## normalized/unit vector
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))


In [6]:
def unit_vector(vector):
    """ 
        Returns the unit vector of the vector.  
    """
    return vector / np.linalg.norm(vector)

### Berechnung der Winkel $\alpha$ und $\beta$


$$\alpha = \angle \left( v_I,e_x \right)$$

$$\beta = \angle \left( v_I,e_y \right)$$

$$\gamma = \angle \left( v_I,e_z \right)$$

dabei sind $e_x= [1,0,0]^\intercal$ und $e_y = [0,1,0]^\intercal$ und $e_z = [0,0,1]^\intercal$

In [7]:
for i,  vector in enumerate(v):
    alpha = angle_rad(vector,np.array([1,0,0]))
    print("Der Winkel alpha für den %s Eigenvektor ist %.3f" %(i+1,np.rad2deg(alpha)))
    beta = angle_rad(vector,np.array([0,1,0]))
    print("Der Winkel beta für den %s Eigenvektor ist %.3f" %(i+1,np.rad2deg(beta)))
    gamma = angle_rad(vector,np.array([0,0,1]))
    print("Der Winkel gamma für den %s Eigenvektor ist %.3f" %(i+1,np.rad2deg(gamma)))
    print("-----------------------")


Der Winkel alpha für den 1 Eigenvektor ist 26.565
Der Winkel beta für den 1 Eigenvektor ist 63.435
Der Winkel gamma für den 1 Eigenvektor ist 90.000
-----------------------
Der Winkel alpha für den 2 Eigenvektor ist 116.565
Der Winkel beta für den 2 Eigenvektor ist 26.565
Der Winkel gamma für den 2 Eigenvektor ist 90.000
-----------------------
Der Winkel alpha für den 3 Eigenvektor ist 90.000
Der Winkel beta für den 3 Eigenvektor ist 90.000
Der Winkel gamma für den 3 Eigenvektor ist 0.000
-----------------------
